"""create marketplace tables

Revision ID: 7b1d2651a9ac
Revises: d092d14e51c6
Create Date: 2026-05-14 23:28:04.749694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b1d2651a9ac'
down_revision: Union[str, Sequence[str], None] = 'd092d14e51c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('SERVICE_COMPANIES', 'FURNITURE_ITEMS', 'MATERIAL_ITEMS', 'RENTAL_ITEMS', name='catalogkind'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('price_range', sa.String(), nullable=True),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_items_kind_active', 'catalog_items', ['kind', 'is_active'], unique=False)
    op.create_index(op.f('ix_catalog_items_id'), 'catalog_items', ['id'], unique=False)
    op.create_table('ai_foreman_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_foreman_threads_id'), 'ai_foreman_threads', ['id'], unique=False)
    op.create_table('marketplace_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('work_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'IN_WORK', 'CLOSED', 'ARCHIVED', name='marketplaceprojectstatus'), nullable=False),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('budget_label', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('address_short', sa.String(length=160), nullable=True),
    sa.Column('full_spec', sa.Text(), nullable=True),
    sa.Column('teaser', sa.String(length=280), nullable=True),
    sa.Column('has_3d', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marketplace_projects_customer_status', 'marketplace_projects', ['customer_user_id', 'status'], unique=False)
    op.create_index('idx_marketplace_projects_status_created_at', 'marketplace_projects', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_projects_id'), 'marketplace_projects', ['id'], unique=False)
    op.create_table('master_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_certificates_id'), 'master_certificates', ['id'], unique=False)
    op.create_table('master_portfolio_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_portfolio_photos_id'), 'master_portfolio_photos', ['id'], unique=False)
    op.create_table('master_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('status_label', sa.String(length=60), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('master_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_user_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('author_display_name', sa.String(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['master_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_master_reviews_master_user_id', 'master_reviews', ['master_user_id'], unique=False)
    op.create_index(op.f('ix_master_reviews_id'), 'master_reviews', ['id'], unique=False)
    op.create_table('ai_foreman_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='aiforemanmessagerole'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['ai_foreman_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_foreman_messages_thread_sent_at', 'ai_foreman_messages', ['thread_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_ai_foreman_messages_id'), 'ai_foreman_messages', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('master_user_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', 'CANCELLED', 'DONE', name='contractstatus'), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['marketplace_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contracts_customer_user_id', 'contracts', ['customer_user_id'], unique=False)
    op.create_index('idx_contracts_master_user_id', 'contracts', ['master_user_id'], unique=False)
    op.create_index('idx_contracts_project_id', 'contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('direct_chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('master_user_id', sa.Integer(), nullable=False),
    sa.Column('last_message_preview', sa.String(length=280), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['marketplace_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_user_id', 'master_user_id', 'project_id', name='uq_direct_chat_customer_master_project')
    )
    op.create_index(op.f('ix_direct_chat_threads_id'), 'direct_chat_threads', ['id'], unique=False)
    op.create_table('master_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('master_user_id', sa.Integer(), nullable=False),
    sa.Column('price_offer', sa.String(), nullable=True),
    sa.Column('duration_offer', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', name='masterbidstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['master_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['marketplace_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'master_user_id', name='uq_master_bid_project_master')
    )
    op.create_index('idx_master_bids_master_user_id', 'master_bids', ['master_user_id'], unique=False)
    op.create_index('idx_master_bids_project_id', 'master_bids', ['project_id'], unique=False)
    op.create_index(op.f('ix_master_bids_id'), 'master_bids', ['id'], unique=False)
    op.create_table('direct_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['direct_chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_direct_chat_messages_thread_sent_at', 'direct_chat_messages', ['thread_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_direct_chat_messages_id'), 'direct_chat_messages', ['id'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_direct_chat_messages_id'), table_name='direct_chat_messages')
    op.drop_index('idx_direct_chat_messages_thread_sent_at', table_name='direct_chat_messages')
    op.drop_table('direct_chat_messages')
    op.drop_index(op.f('ix_master_bids_id'), table_name='master_bids')
    op.drop_index('idx_master_bids_project_id', table_name='master_bids')
    op.drop_index('idx_master_bids_master_user_id', table_name='master_bids')
    op.drop_table('master_bids')
    op.drop_index(op.f('ix_direct_chat_threads_id'), table_name='direct_chat_threads')
    op.drop_table('direct_chat_threads')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index('idx_contracts_project_id', table_name='contracts')
    op.drop_index('idx_contracts_master_user_id', table_name='contracts')
    op.drop_index('idx_contracts_customer_user_id', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_ai_foreman_messages_id'), table_name='ai_foreman_messages')
    op.drop_index('idx_ai_foreman_messages_thread_sent_at', table_name='ai_foreman_messages')
    op.drop_table('ai_foreman_messages')
    op.drop_index(op.f('ix_master_reviews_id'), table_name='master_reviews')
    op.drop_index('idx_master_reviews_master_user_id', table_name='master_reviews')
    op.drop_table('master_reviews')
    op.drop_table('master_profiles')
    op.drop_index(op.f('ix_master_portfolio_photos_id'), table_name='master_portfolio_photos')
    op.drop_table('master_portfolio_photos')
    op.drop_index(op.f('ix_master_certificates_id'), table_name='master_certificates')
    op.drop_table('master_certificates')
    op.drop_index(op.f('ix_marketplace_projects_id'), table_name='marketplace_projects')
    op.drop_index('idx_marketplace_projects_status_created_at', table_name='marketplace_projects')
    op.drop_index('idx_marketplace_projects_customer_status', table_name='marketplace_projects')
    op.drop_table('marketplace_projects')
    op.drop_index(op.f('ix_ai_foreman_threads_id'), table_name='ai_foreman_threads')
    op.drop_table('ai_foreman_threads')
    op.drop_index(op.f('ix_catalog_items_id'), table_name='catalog_items')
    op.drop_index('idx_catalog_items_kind_active', table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
