"""bind snapshots to marketplace projects

Revision ID: c59f1fbe289e
Revises: 7b1d2651a9ac
Create Date: 2026-05-28 15:32:01.751963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59f1fbe289e'
down_revision: Union[str, Sequence[str], None] = '7b1d2651a9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_snapshots', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('apartment_snapshots', sa.Column('saved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('apartment_snapshots', sa.Column('editor_role', sa.String(length=30), nullable=True))
    op.alter_column('apartment_snapshots', 'apartment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('apartment_snapshots', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_snapshots_project', 'apartment_snapshots', ['project_id'], unique=False)
    op.create_index('idx_snapshots_project_version', 'apartment_snapshots', ['project_id', 'version'], unique=False)
    op.create_foreign_key(None, 'apartment_snapshots', 'users', ['saved_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'apartment_snapshots', 'marketplace_projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartment_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'apartment_snapshots', type_='foreignkey')
    op.drop_index('idx_snapshots_project_version', table_name='apartment_snapshots')
    op.drop_index('idx_snapshots_project', table_name='apartment_snapshots')
    op.alter_column('apartment_snapshots', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('apartment_snapshots', 'apartment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('apartment_snapshots', 'editor_role')
    op.drop_column('apartment_snapshots', 'saved_by_user_id')
    op.drop_column('apartment_snapshots', 'project_id')
    # ### end Alembic commands ###
