"""add user maps

Revision ID: d841452b54a5
Revises: c59f1fbe289e
Create Date: 2026-06-04 20:16:49.455836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd841452b54a5'
down_revision: Union[str, Sequence[str], None] = 'c59f1fbe289e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('map_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_maps_json', 'user_maps', ['map_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_user_maps_user_id', 'user_maps', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_maps_id'), 'user_maps', ['id'], unique=False)
    op.create_index(op.f('ix_user_maps_user_id'), 'user_maps', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_maps_user_id'), table_name='user_maps')
    op.drop_index(op.f('ix_user_maps_id'), table_name='user_maps')
    op.drop_index('idx_user_maps_user_id', table_name='user_maps')
    op.drop_index('idx_user_maps_json', table_name='user_maps', postgresql_using='gin')
    op.drop_table('user_maps')
    # ### end Alembic commands ###
